---
- name: server security patching
  hosts: all_targets
  become: true
  tasks: 
    - name: update package update_cache
      package: 
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"
      register: deb_update  
    - name: Upgrade all packages
      apt:
        upgrade: dist 
        autoremove: yes
        autoclean: yes 
      when: ansible_os_family == "Debian" 
    - name: Install unattended-upgrades
      apt:
        name: unattended-upgrades
        state: present
      when: ansible_os_family == "Debian"  
    - name: Enable unattended-upgrades
      command: dpkg-reconfigure -f noninteractive unattended-upgrades
      when: ansible_os_family == "Debian"
   
    - name: update all packages (RedHat)  
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"  
### Add Cron job so it can run every month ###
    - name: install cron (Redhat)
      dnf:
        name: cronie 
        state: present
      when: ansible_os_family == "RedHat" 
    - name: Enable cron 
      service:
        name: crond
        state: started
        enabled: yes   
      when: ansible_os_family == "RedHat"  
    - name: install cron on Debian 
      apt:
        name: cron
        state: present
        update_cache: yes 
      when: ansible_os_family == "Debian"   
    - name: Ensure cron is running
      service:
        name: cron 
        state: started
        enabled: yes 
      when: ansible_os_family == "Debian"  
      
      
    - name: create a schedule monthly patch ( Debian) 
      cron:
        name: "Monthly server patching"
        minute: "0"
        hour: "2"
        day: "1"
        job: "apt update && apt upgrade -y >> /var/log/monthly_patching.log 2>&1"
      when: ansible_os_family == "Debian"
    - name: create a monthly schedule (RedHat) 
      cron:
        name: "Monthly security patching"
        minute: "0"
        hour: "3"
        day: "1"
        job: "dnf update && dnf upgrade -y >> /var/log/patching.log 2>&1"
      when: ansible_os_family ==  "RedHat"
